### ISSUE TITLE
Add option to not generate or separate client api code

### ISSUE THREAD

**Issue by dradetsky** [oazapfts/oazapfts#22]
If I understand correctly, oazapfts generates a great deal of code and types (largely from `ApiStub.ts`) for use by a client of the API. This is fine, and I imagine I'll want to use it eventually, but for use in a server-side context, I would prefer to generate only code which might potentially be used by the server, such as:

- typescript types/interfaces for the objects defined in the schema
- typescript function types for the operationIds declared in the schema

NOTE: I don't believe you currently generate function types for the operationIds, and I'm not requesting that this be added.

It would be nice for a lot of purposes, such as easy understanding/debugging by users, or reducing the size of generated images, if I could either generate only the server-relevant code, or put the server-relevant code and client-relevant code in separate files.

I briefly looked at the code, hoping to find something like "print the contents fo the file ApiStub.ts to the output string we're building up" but it looks like the way its done is somewhat more complicated, so I can't just easily do it myself (without putting more time into trying to understand it).

For my use case, it wouldn't be necessary to have an entire cli argument setup with option parsing and whatnot. I'd be perfectly satisfied with an environment variable so I could do something like

```
OAZAPFTS_SERVER_CODE_ONLY=true npx oazapfts path/to/api.yaml path/to/output.ts
```

although I wouldn't necessarily discourage you from adding an argument setup or support for a project configuration file or whatever.

**Comment by fgnass** [comment]
Some thoughts: In the [next](https://github.com/cellular/oazapfts/tree/next) release the files generated by oazapfts will contain much less code as everything from ApiStub.ts has been moved into a runtime dependency. So the code is a lot easier to browse.

To understand your use-case: You have an existing API spec and want to implement it manually? Or would you write the API spec as you go? In that case, have you considered using a tool like [tsoa](https://github.com/lukeautry/tsoa)?

**Comment by dradetsky** [comment]
The first. I specifically want to write the API spec by hand and then implement it manually. I also want to reuse as much of what's already specified in the spec without having to rewrite it and/or manually match it to the code. For example, if I've already said that `POST /some/path` takes a request body with certain fields, I shouldn't write a typescript type with those fields by hand.

There are any number of tools that generate a spec from your app (for generating a swagger-ui page or compiling into a client), but very few tools aimed at reusing a spec that you write by hand.

**Comment by ChuckJonas** [comment]
I also have a use case where I want to generate the types without the client.

We are using `RTKquery` code generation on our front end (which uses this library)

On our backend, we are developing using typescript with a "Open ApI schema first" approach.  Meaning, we handwrite our OpenAPI spec, but would like to generate types to codes against in our api implementations. 

Basically, both the Frontend and backend run type generation against the OPAI spec.

Right now, we are using `typeconv` for the backend, which means our type definitions are slightly different (and it doesn't generate request and response, only components/schema).

It would be great if we could leverage this library for types only with having the extra client code.

**Comment by fgnass** [comment]
I'm closing this for now and would recommend https://github.com/ferdikoomen/openapi-typescript-codegen for use-cases like this.
