### ISSUE TITLE
Repetitive code between `function createKeywordType` and `const keywordType`

### ISSUE THREAD

**Issue by lindapaiste** [oazapfts/oazapfts#237]
I was looking at the source code and I noticed that the same mapping of keyword name to TS node is happening in two places in the `tscodegen.ts` file. `export function createKeywordType` and `export const keywordType` have the same logic and can definitely be combined.  

It seems as though the `function createKeywordType` is not actually used anywhere.  Can it be deleted?  Or is it part of the public API?

https://github.com/cellular/oazapfts/blob/0f6225941973bada228b27d1fb60a09462d40a60/src/codegen/tscodegen.ts#L22-L41

https://github.com/cellular/oazapfts/blob/310117038b6a5119c8a121063d9f4d6f36f43b59/src/codegen/tscodegen.ts#L43-L55

I haven't dug through the entire codebase but I am inclined to think that the explicit type annotation on `const keywordType` is more harmful than helpful, as it:

- Allows any `string` key, not just the valid keys.
- Prevents intellisense suggestions.
- Broadens the type of each property to the union rather than its specific type.

 There are actually a few places in the code that use `cg.keywordType.void` even though it doesn't exist!  This would be an error without the explicit type on `keywordType`.

**Comment by fgnass** [comment]
Fixed by #346
