### ISSUE TITLE
Conversion of reserved words 

### ISSUE THREAD

**Issue by goququ** [oazapfts/oazapfts#329]
Hi team!

I am trying to generate OpenAPI specification for k8s. But client file is invalid because of "continue" parameter (reserved word).

<img width="753" alt="image" src="https://user-images.githubusercontent.com/12967830/202675111-cc9d7d5f-2b48-430e-bd69-65139d76abc3.png">

How to reproduce: 

`npx oazapfts https://gist.githubusercontent.com/goququ/e3d8f96db1eb19e570dee833c41549a5/raw/291cf061ad3425bdf2860a9f5ee3c83674d249d6/k8s.openapi.yaml ./k8s.ts --optimistic`

**Comment by Xiphe** [comment]
Oh, that's an interesting edge case. Thanks for reporting 👍

**Comment by fgnass** [comment]
Closed by 90c2610
