### ISSUE TITLE
oazapfts generates the code that can't be compiled

### ISSUE THREAD

**Issue by papirosko** [oazapfts/oazapfts#339]
example of generated code:
```
export function getAccountsByIdDirectPartners(id: string, requireVersion: string, { id, isAscending, orderBy, page, pageSize, search }: {
    id?: string;
    isAscending?: boolean;
    orderBy?: string;
    page?: number;
    pageSize?: number;
    search?: string;
} = {}, opts?: Oazapfts.RequestOpts)
```
with error:
```
error TS2300: Duplicate identifier 'id'.
```
you can see that with the spread feature it generates the code with the same parameter names (`id` in this case).

can you please generate it like this?

```
export function getAccountsByIdDirectPartners(id: string, requireVersion: string, optionalParams: {
    id?: string;
    isAscending?: boolean;
    orderBy?: string;
    page?: number;
    pageSize?: number;
    search?: string;
} = {}, opts?: Oazapfts.RequestOpts)
```

**Comment by Xiphe** [comment]
Hi @papirosko thanks for reporting this issue. I agree that this should be solved.

I'd prefer to use some sort of duplicate detection instead of not destructuring the params. Not because I'm a huge fan of destructuring but because `optionalParams` would then be the next candidate to cause naming conflicts.

Could you please provide a version of the spec file that caused this issue with only the method suffering from this in it?

**Comment by papirosko** [comment]
```
{
  "openapi": "3.0.1",
  ...
  "/accounts/{id}/direct/partners": {
      "get": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "title": "id",
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "query",
            "schema": {
              "title": "id",
              "type": "string"
            }
          },
```

**Comment by papirosko** [comment]
the easiest solution.
The name collision may happen if you have same name in path and query and header. e.g. `id` in the example above. Inside the group (e.g. query params) there is no collision.

so the fix will be like (in pseudo code):
```
        const namesCount = parameters.groupBy(p => p.name);
        this.parameters = parameters.map(p => {
            if (namesCount.get(p.name).exists(c => c.size > 1)) {
                return p.copy({
                    name: `${p.in}${Method.capitalize(p.name)}`
                })
            } else {
                return p;
            }
        });
```

**Comment by Xiphe** [comment]
Yeah, we already do this for other parts (like the [fix added recently for enum conflicts](https://github.com/cellular/oazapfts/pull/340))

I won't have the time to fix this soon as I'm wrapping up my year currently and will not be available in december
