### ISSUE TITLE
can't generate TS enum for openapi enum ref 

### ISSUE THREAD

**Issue by trim21** [oazapfts/oazapfts#367]
re-produce: https://github.com/trim21/oazapfts/commit/de17782a9981d1ca643df86c222765294ad4de35

it generate union if it's used in `$ref`

**Comment by Xiphe** [comment]
Sorry, no have not found the time to look into this and then it fell of my list. Thanks for the reminder. Will try to have a look in the next days.

**Comment by Xiphe** [comment]
There was not so much info towards the expected state in this issue and the reproduction. So I assumed the following:

### Problem:  

Currently, when creating a client with the `--useEnumType` and the schema uses a referenced enum, that type is created as a union. Where we would expect that to also be a native ts enum.

Is that correct?

---


If so, can you please check out https://github.com/oazapfts/oazapfts/pull/444 and see if it solves the problem on your end?
