### ISSUE TITLE
Support `readOnly` and `writeOnly`

### ISSUE THREAD

**Issue by olivierbeaulieu** [oazapfts/oazapfts#382]
oazapfts doesn't seem to support these two properties from OAS. It would be a hugely helpful feature to support, as today we need to create distinct schemas for requests & responses.

Example: Given the OpenAPI spec below, the generated `postThing` function should have `read_only_prop` should only be present in the response, and `write_only_prop` should only be present in the request.

```json
{
  "info": {
    "title": "Example"
  },
  "openapi": "3.0.2",
  "servers": [
    {
      "url": "https://example.com"
    }
  ],
  "paths": {
    "/post-thing": {
      "post": {
        "operationId": "post_thing",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ExampleSchema"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ExampleSchema"
                }
              }
            },
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ExampleSchema": {
        "properties": {
          "read_only_prop": {
            "type": "string",
            "readOnly": true
          },
          "write_only_prop": {
            "type": "boolean",
            "writeOnly": true
          }
        },
        "type": "object"
      }
    }
  }
}
```

**Comment by Xiphe** [comment]
That's an interesting one! Agree that it would be cool if we could support this somehow.

In TypeScript these would still need to be two different entities since the language does not know about the context in which the types are used. This means we need to come up with a naming schema for those and in the generated code you'd still have something like this:

```ts
type ExampleSchemaReq {
  write_only_prop: boolean
}
type ExampleSchemaRes {
   read_only_prop: boolean
}
```

Any suggestions for naming? And anyone keen to implement this?

**Comment by jonkoops** [comment]
Interesting, perhaps we could solve this with generics somehow? Or perhaps that would only make things more complicated.

As for naming, probably best to stick to the schema naming convention as much as possible. So perhaps `ExampleSchemaRead` and `ExampleSchemaWrite`?

**Comment by jonkoops** [comment]
Alternatively, we could keep the type representation for the schema in a more complex type (closer to spec) that contains all the information for the fields (such as `type`, `writeOnly`, `readOnly`) and provide utility types that can 'serialize' this to a 'plain' type when returned from methods.

```ts
function fetchUser(id: string):  ReadonlySchema<ExampleSchema>
function saveUser(id: string, newName: string):  WriteonlySchema<ExampleSchema>
```

**Comment by Xiphe** [comment]
I think just using `ExampleSchemaRead` and `ExampleSchemaWrite` and duplicate everything that they share is probably both: the easiest to implement and the easiest to work with.

What I like about your second approach is that is protects us from naming collisions. For example when the spec also has a `ExampleSchemaRead` type.

**Comment by jonkoops** [comment]
Yeah, going for dedicated type I think is the easiest way to accomplish this. Ideally we'd keep the base `ExampleSchema` around and extend it from the `Read` and `Write` variants. So considering the following schema:

```json
{
  "ExampleSchema": {
    "properties": {
      "type": "object",
      "always_present": {
        "type": "string"
      },
      "read_only_prop": {
        "type": "string",
        "readOnly": true
      },
      "write_only_prop": {
        "type": "boolean",
        "writeOnly": true
      }
    }
  }
}
```

I would expect:

```ts
interface ExampleSchema {
  always_present: string
}

interface ExampleSchemaRead extends ExampleSchema {
  read_only_prop: string
}

interface ExampleSchemaWrite extends ExampleSchema {
  write_only_prop: string
}
```

**Comment by Xiphe** [comment]
Yeah I like that 👍

**Comment by olivierbeaulieu** [comment]
Handling nested schemas might be trickiest part in here. I took a stab at implementing this in another library, openapi-typescript, here: https://github.com/drwpow/openapi-typescript/issues/604#issuecomment-1430683390

Using generics made the implementation very easy, and allows to support read/write quite naturally without needing to generate everything 3x.

**Comment by jonkoops** [comment]
That is a good point indeed. I would imagine we'd need to refactor our internals quite a bit to handle the generic approach.
