### ISSUE TITLE
semantic release?

### ISSUE THREAD

**Issue by Xiphe** [oazapfts/oazapfts#397]
@fgnass you know that I'm a big fan of [semantic release](https://semantic-release.gitbook.io/semantic-release/) would it be fine with you if we add it to the CI? (Would need your support to set up the NPM secret).

I'd personally like this to save some time releasing new versions and reducing manual copy-paste work notifying PRs and creating the changelog.

If we decide to not go with it, is there a way to allow me to push to `main`? So I don't have to do a [PR to update the version number in package.json](https://github.com/oazapfts/oazapfts/pull/396)

Would also be interested in @jonkoops opinion.

**Comment by fgnass** [comment]
@Xiphe +1 for adding the semantic release bot. I made you an admin, so you can bypass the branch protection rules.

**Comment by jonkoops** [comment]
Yes, I am all for automating this +1
