### ISSUE TITLE
allOf with inheritance

### ISSUE THREAD

**Issue by twastvedt** [oazapfts/oazapfts#422]
I'd like to combine inheritance and the discriminator in my API, as this describes: https://redocly.com/docs/resources/discriminator/#allof-for-inheritance. It looks like oazapfts only supports using the discriminator with oneOf though. Is that correct? Is there an alternative?

Here's a rephrasing of the example from the link:
```
Vehicle:
  type: object
  description: Vehicle
  discriminator:
    propertyName: powerSource
    mapping:
      electricity: '#/components/schemas/ElectricVehicle'
      gasoline: '#/components/schemas/FueledVehicle'
      human-energy: '#/components/schemas/PedaledVehicle'
  properties:
    vehicleType:
      description: The type of vehicle.
      type: string
      example: bicycle
    idealTerrain:
      type: string
      example: roads
    powerSource:
      description: How is the vehicle powered.
      type: string
      example: pedaling
PedaledVehicle:
  allOf:
    - $ref: '#/components/schemas/Vehicle'
    - type: object
      description: Pedaled Vehicle
      properties:
        topSpeed:
          description: The top speed in kilometers per hour rounded to the nearest integer.
          type: integer
          example: 83
        range:
          description: The 95th percentile range of a trip in kilometers.
          type: integer
          example: 100

**Comment by Xiphe** [comment]
Yeah, it might very well be that this is not supported. I would need to dig deeper into this as it's not obvious from your example and the linked text what the expected TS output should look like...

Any help appreciated

**Comment by twastvedt** [comment]
Ahah. Right. I retract my request! I think for the TypeScript output to work, the discriminating type and the base type need to be separate. So:

```
VehicleBase:
  type: object
  properties:
    powerSource:
      type: string
    ...
Vehicle:
  oneOf:
    $ref: '#/components/schemas/ElectricVehicle'
    $ref: '#/components/schemas/FueledVehicle'
    $ref: '#/components/schemas/PedaledVehicle'
  discriminator:
    propertyName: powerSource
    mapping:
      electricity: '#/components/schemas/ElectricVehicle'
      gasoline: '#/components/schemas/FueledVehicle'
      human-energy: '#/components/schemas/PedaledVehicle'
PedaledVehicle:
  allOf:
    - $ref: '#/components/schemas/VehicleBase'
    - type: object
      properties:
        ...
```
This **does** work in oazapfts.

I came here because I'm trying to write an API that code gens in both oazapfts and NSwag (C#). (In C#, the discriminator manifests as properties on the class, so the base class and the discriminator _can_ be the same class.) Unless this doesn't look right to you, I'll head back to NSwag and see if I can figure out how to make it work with the above approach. Thanks for your time!

**Comment by Xiphe** [comment]
Sweet, glad to hear you found a solution!

**Comment by twastvedt** [comment]
OK, I'm back, with one more thought. Could an extra discriminator type be created by oazapfts? Something like:

```typescript
export type Vehicle = {
    vehicleType: string;
    idealTerrain: string;
    powerSource: string;
}

export type VehicleDiscriminator = ( { powerSource: "electricity" } & ElectricVehicle ) 
  | ( { powerSource: "gasoline" } & FueledVehicle ) 
  | ( { powerSource: "human-energy" } & PedaledVehicle );

export type PedaledVehicle = Vehicle & {
    topSpeed: number;
    range: number;
}
``` 
Then properties of this type would be of type `VehicleDiscriminator` instead of `Vehicle`. Or, alternatively, we could name the base class differently, so we'd have `Vehicle` (the discriminator, and the property type) and `VehicleBase` (the base class).

**Comment by Xiphe** [comment]
Welcome back ;)

Would that be generated from the spec you've posted earlier or is that a different approach?

**Comment by twastvedt** [comment]
> Would that be generated from the spec you've posted earlier or is that a different approach?

From the spec at the top.

**Comment by Xiphe** [comment]
From how I understand this I'd map the schema to this:

```

type VehicleBase = {
  powerSource: string;
};

interface PedaledVehicle extends VehicleBase {
  pedaledOnlyProp: string;
}

interface ElectricVehicle extends VehicleBase {
  electricOnlyProp: string;
}

interface FueledVehicle extends VehicleBase {
  fueledOnlyProp: string;
}

type Vehicle =
  | ({ powerSource: "electricity" } & ElectricVehicle)
  | ({ powerSource: "gasoline" } & FueledVehicle)
  | ({ powerSource: "human-energy" } & PedaledVehicle);

// example usage
function doSomethingWithVehicle(vehicle: Vehicle) {
  // discriminate based on powerSource
  switch (vehicle.powerSource) {
    case "human-energy":
      console.log(vehicle.pedaledOnlyProp);
      break;
    case "electricity":
      console.log(vehicle.electricOnlyProp);
      break;
    case "gasoline":
      console.log(vehicle.fueledOnlyProp);
      break;
  }
}
```

That said, looking at the TS code, it's strange to me that the discriminating property is not part of the XVehicle classes... to me it would look a lot more useful if it's modeled like this:

```ts
export type VehicleBase = {
  powerSource: string;
};

interface PedaledVehicle extends VehicleBase {
  powerSource: "human-energy";
  pedaledOnlyProp: string;
}

interface ElectricVehicle extends VehicleBase {
  powerSource: "electricity";
  electricOnlyProp: string;
}

interface FueledVehicle extends VehicleBase {
  powerSource: "gasoline";
  fueledOnlyProp: string;
}

type Vehicle = ElectricVehicle | PedaledVehicle | FueledVehicle;

// example usage
function doSomethingWithVehicle(vehicle: Vehicle) {
  // discriminate based on powerSource
  switch (vehicle.powerSource) {
    case "human-energy":
      console.log(vehicle.pedaledOnlyProp);
      break;
    case "electricity":
      console.log(vehicle.electricOnlyProp);
      break;
    case "gasoline":
      console.log(vehicle.fueledOnlyProp);
      break;
  }
}
```

I currently don't have much more time to invest in this, but it would be worth exploring:

1. if the latter model can be achieved with what we already have
2. if the discriminator pattern is common enough that we should add support for it in oazapfts

**Comment by twastvedt** [comment]
> 1.     if the latter model can be achieved with what we already have
> 2.     if the discriminator pattern is common enough that we should add support for it in oazapfts

Totally agree that your second model would be more useful, nicer, etc. I suspect that is possible with the current oazapfts, but as you say, wouldn't involve discriminators. I'm not sure how to evaluate #2, but I think it would be worth exploring because in other languages (that we also use with this API) the discriminator is quite useful (In C# or Java the code generators create deserialization logic which maps directly into the child class types).

I did look at the oazapfts code a bit. I'd be happy to pursue this more (slowly, as I have time), but I didn't immediately see how to approach it. Not anywhere near an expert, but the issue I ran into was how to make the same ref point to two different types (in the above example, a property containing a Vehicle ref would point to Vehicle, but the ref in PedaledVehicle's allOf would point to VehicleBase. As far as I can tell there's a pretty strict 1:1 relationship between schema and type, I think? If it's ok to break that, maybe we could add an options argument to `getTypeFromSchema` which would control that differentiation?

**Comment by Xiphe** [comment]
To be honest, the implementation of this lib is also something I need to wrap my head around any time i'm doing/reviewing something more complex. So I'm afraid I cant be of much help unless I spend some time exploring - at which point I then could also go ahead and implement the feature :)

**Comment by goququ** [comment]
Faced with same issue, very sad ='(

**Comment by Xiphe** [comment]
Sorry to hear that @goququ and thanks for letting us know, helps prioritizing 👍

**Comment by bdm-k** [comment]
Hi there. I'm currently working on this issue. In my implementation, the schemas at the top will map to the following:
```typescript
export type VehicleBase = {
  vehicleType?: string;
  idealTerrain?: string;
  powerSource?: string;
};
export type PedaledVehicle = VehicleBase & {
  topSpeed?: number;
  range?: number;
};
export type Vehicle =
  | ({ powerSource: "electricity" } & ElectricVehicle)
  | ({ powerSource: "gasoline" } & FueledVehicle)
  | ({ powerSource: "human-energy" } & PedaledVehicle);
```
Compared to the second model proposed by @Xiphe, there are two key differences.  

1. `PedaledVehicle` is not an interface but an intersection type. The reason for this is to avoid making drastic changes to the interpretation of `allOf`. Additionally, now that #451 has been merged, interfaces are no longer generated. I believe it's better to keep the current situation, where only type aliases are used.  
2. Second, `powerSource` is not included in `PedaledVehicle`. This is because I wanted to use `getUnionType` to generate `Vehicle` for the sake of simplicity. When using the function, it is natural to generate a type in the form shown above.

Any thoughts on my proposal? If it looks good, I'll go ahead and create a PR.

**Comment by Xiphe** [comment]
Hey @bdm-k so cool that you decided to move this forward. 

Fully agree with your first point sticking with `type` makes the implementation of this a lot easier.

I'm a little confused to why all properties are optional in your example. I don't think that should be the case given the example schema we're working with here, right?

As with the second point, I think this will lead to confusion in case such a type is being used as an parameter for a call or somewhere outside of oazapfts:

```ts
// api.ts
export type VehicleBase = {
  powerSource: string;
};
export type PedaledVehicle = VehicleBase & {
  topSpeed: number;
};
export type Vehicle =
  | ({ powerSource: "electricity" } & ElectricVehicle)
  | ({ powerSource: "gasoline" } & FueledVehicle)
  | ({ powerSource: "human-energy" } & PedaledVehicle);
  
export function createVehicle(vehicle: Vehicle, opts?: Oazapfts.RequestOpts) {}
```

When I then use it like this:

```ts
import { PedaledVehicle, createVehicle } from './api.ts'

// this is a valid PedaledVehicle
const myBike: PedaledVehicle = { powerSource: 'my-legs', topSpeed: 45 };

// but it's not actually a Vehicle because powerSource is more strictly typed here
avait createVehicle(myBike);
```

That said: I see your point, when the implementation for what you're proposing is a lot more straight forward then let's first give that a shot!

**Comment by Xiphe** [comment]
Ah, yeah you're right. I sometimes get confused on the required vs. optional flags in different specs/apis :)
Don't think the behavior should be changed for this particular case. 

Thanks you for putting in the afford! Looking forward to your PR 👍

**Comment by twastvedt** [comment]
Thank you @bdm-k and @Xiphe! We appreciate your work on this!
