### ISSUE TITLE
`Content-Type` Header Is not updated

### ISSUE THREAD

**Issue by kmirojo** [oazapfts/oazapfts#452]
Good day 👋 
I'm using `oazapfts@4.7.4` to implement my fetch calls from an `Open API` specification file in a typescript client.

I need to configure the `oazapfts` request to send whole body unicode/utf-8, but when I try to do it, it is overrriten by the default headers configuration.

In my API configuration file I'm setting the header in multiple ways:
```ts
defaults.headers = {
      "Content-Type": "application/json; charset=UTF-8",
};
//
defaults.headers["Content-Type"] = application/json; charset=UTF-8";
```

But every time the fetch call header looks like `Content-Type: "application/json"`.

Am I doing something wrong? (most likely)
Or is there no way to set the header `Content-Type` header according to my needs?

**Comment by Xiphe** [comment]
Hi @kmirojo 

You're right, it seems as if the Content-Type header currently can not be overwritten: https://github.com/oazapfts/oazapfts/blob/main/src/runtime/index.ts#L114-L115

I'm not entirely sure how to best solve this. But I tend to say we should switch those lines. Any feedback/input very welcome

**Comment by kmirojo** [comment]
Thanks a lot for taking the time to look at this @Xiphe 🙏 .
We will be attentive to the implementation of the suggested solution whenever it's possible or if you require more information from our side,

**Comment by Xiphe** [comment]
Happy to review a PR on this 👍

**Comment by kmirojo** [comment]
Thanks @Xiphe 
I'll create a PR for this issue, but we were wondering, how soon would you guys publish another release if the PR meets the acceptance criteria.

**Comment by Xiphe** [comment]
We're utilizing [semantic release](https://semantic-release.gitbook.io/semantic-release/). So when the change is in `main` there will be a release.

And given the small non-intrusive nature of the change I see no blockers that would delay a swift merge of the PR.
