### ISSUE TITLE
Feature request: Add support for application/ld+json

### ISSUE THREAD

**Issue by Richard87** [oazapfts/oazapfts#46]
Hi!

I would love to have support for application/ld+json, and prefer it when generating types.
(https://github.com/rtk-incubator/rtk-query-codegen/issues/28) 

Would you accept a PR for that, or is it out of scope? :) 

And if so, have any pointers to where I should start? :)

**Comment by fgnass** [comment]
It should be as simple as adding it to https://github.com/cellular/oazapfts/blob/main/src/codegen/generate.ts#L23.

That being said, it might also be a good idea to map every content-type that contains `json` to `json` without having to add it explicitly.

**Comment by fgnass** [comment]
Closed by #346
