### ISSUE TITLE
`handle` helper returns `never` type for non-array objects

### ISSUE THREAD

**Issue by eric-carlsson** [oazapfts/oazapfts#460]
#### Description

I have an OpenAPI spec that contains endpoints similar to 

```yaml
paths:
  /cats:
    get:
      operationId: listCats
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cat"

  /cats/{id}:
    get:
      operationId: getCat
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cat"
```

The type signatures of the generated functions corresponding to these operations are

```ts
function listCats(opts?: RequestOpts | undefined): Promise<WithHeaders<{
    status: 200;
    data: Cat[];
}>>

function getCat(id: number, opts?: RequestOpts | undefined): Promise<WithHeaders<{
    status: 200;
    data: Cat;
}>>
```

When using the `handle` helper like so

```ts
const cats = await handle(listCats(), {
  200: (cats) => cats,
}

const cat = await handle(getCat(), {
  200: (cat) => cat
}
```
we expect the types of `cats` and `cat` to be `Cat[]` and `Cat` respectively.

The issue I am having is that while the type of `cats` is inferred correctly, the type of `cat` becomes `never`. This is only the case for non-array types.

#### Comments

Looking into the type declarations used by `handle`, we find this generic type that is used to determine the return type of `handle`.

```ts
export type FunctionReturnType<T> = T extends (args: any[]) => any ? ReturnType<T> : never;
```

I'm far from a typescript expert, but as I understand it, this will equate to "if the handler type extends `(args: any[]) => any`, then use the return type of this handler and otherwise use `never`". The key detail here is the type of `args`, `any[]`. This will only match arrays, and hence, we get a `never` type for handlers that return values that are not arrays (such as singular objects). Changing this type to

```ts
export type FunctionReturnType<T> = T extends (args: any) => any ? ReturnType<T> : never;
```

appears to resolve the issue. The type of `cat` is now correctly `Cat`, and the type of handlers that have no return values remains `never`, as it should.

I can submit a PR with this fix, but it would be appreciated if someone can lay eyes on this to make sure I'm not missing something.

**Comment by Xiphe** [comment]
Hey @eric-carlsson I'm having trouble reproducing the issue. 

I've added these lines to the [`should call the matching handler` test case](https://github.com/oazapfts/oazapfts/blob/main/demo/api.test.ts#L233-L243)

```ts
const cat = await handle(api.getPetById(1), {
  200: (cat) => cat
});
```

which should essentially surface the issue (right?) and the `cat` is of type `api.Pet`.

Could you help me reproducing? 

---

Besides that I don't see a reason against your adjustment to the `FunctionReturnType` in fact I beliefe that @fgnass might have wanted to type it like `export type FunctionReturnType<T> = T extends (...args: any[]) => any ? ReturnType<T> : never;` ?

Looking forward to further input from your end 👍

**Comment by eric-carlsson** [comment]
> which should essentially surface the issue (right?) and the `cat` is of type `api.Pet`.

Hmm, I am seeing the same issue with the example you provided. 

Checked out `main`, and ran `npm ci`. Using your example, I get 

```ts
const cat = await handle(api.getPetById(1), {
  200: (cat) => {
    console.log(cat.name) // Ok
    return cat
  },
});
console.log(cat.name); // Property 'name' does not exist on type 'never'.
```

Adding a test that's something like any of the following should trigger the issue:

```ts
  it("should not type response as never", async () => {
    const res = await handle(api.getPetById(1), {
      200: (res) => res,
    });
    //@ts-expect-error
    res satisfies never;
    expect(res).toBeDefined();
  });

  it("should type response as Pet", async () => {
    const res = await handle(api.getPetById(1), {
      200: (res) => res,
    });
    expect(typeof res.name).toBe("string");
  });
```



> in fact I believe that @fgnass might have wanted to type it like this: ...

Yep, that makes a lot of sense! I'm not aware of a situation when the handler will receive multiple arguments, but nevertheless that was probably the original intention, and a prettier solution.

**Comment by Xiphe** [comment]
Thank you. Something seemed off with my setup. Made a fresh install and now i'm getting the error as well. 

Let's please go with the `...args: any[]` solution and one of the tests you've mentioned.

Do you want to create a PR for this or do you want me to do it?

**Comment by eric-carlsson** [comment]
Sure, sounds good! See the linked PR.
