### ISSUE TITLE
Error when trying to build typescript project 

### ISSUE THREAD

**Issue by wshbair** [oazapfts/oazapfts#482]
By running the command of `rimraf dist && tsc` I got the following error: 
```
node_modules/@tzkt/sdk-api/build/main/index.d.ts:5:27 - error TS2307: Cannot find module '@tzkt/oazapfts/runtime' or its corresponding type declarations.

5 import * as Oazapfts from '@tzkt/oazapfts/runtime';
                            ~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in node_modules/@tzkt/sdk-api/build/main/index.d.ts:5
```

Any help is appreciated

**Comment by Xiphe** [comment]
Hey @wshbair 

`@tzkt/oazapfts` indicates that your project uses a [fork of this project](https://github.com/tzkt/oazapfts). 
The code of this repo is on npm as `oazapfts`.

Not much I can do with this. You might want to ask @tzkt for help or move back to the mainstream. 

In general this seems like either some `node_modules` not installed correctly or tsconfig related stuff.

Closing as I don't think we can help. Please re-open when the problem persists with `oazapfts` and you can provide more detailed steps to reproduce.
