### ISSUE TITLE
Support `type` as an array

### ISSUE THREAD

**Issue by mattoni** [oazapfts/oazapfts#497]
I'm using a downstream library (RTK Query) and have recently updated my spec to 3.1.0.  My spec mostly generates, but it seems multiple values for types (the recommended way to handle 'null' values) is not generating correctly:

```
type:
    - "object"
    - "null" 
```

When run, I get only the 'object' type, and null isn't valid here. Is this something that can be supported?

For more examples I have an issue on RTK here: https://github.com/reduxjs/redux-toolkit/issues/3814, which is where I was redirected to this repository.

Thank you!

**Comment by misterjame** [comment]
+1

**Comment by Xiphe** [comment]
Thank you for opening the issue. Can you please provide an example schema that we can use to illustrate the behavior?

**Comment by mattoni** [comment]
Sure, see the Github v3 REST API here: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghes-3.0/ghes-3.0.yaml

You'll find many examples of things like 
```
  webhook_secret:
    type:
    - string
    - 'null'
```
