### ISSUE TITLE
Please improve documentation

### ISSUE THREAD

**Issue by homer-jay** [oazapfts/oazapfts#50]
I'm having a hard time trying to set some custom http headers. If I set them globally, apparently the library is doing preflight and the server is not responding with the proper headers. If however I set the headers in the json call, then it does a GET, but also messes the headers. 
I'm also having lots of trouble with CORS. There is no indication whatsoever in your README on how to deal with this.
I've read the runtime source code from top to bottom and I was unable to see where in the heck are the actual network calls being made. Debugging I end in a so-called `fetch` function that I wasn't able to find in the source code.

All these are problems that I don't expect you to solve in this issue. But please, improve the documentation a bit. I've lost 2 hours debugging.

**Comment by martijn10kb** [comment]
Please do, just wasted some more time here...

**Comment by fgnass** [comment]
I've updated the README which will hopefully address your concerns: 4dbba5f6f8ea817dacd21dd8c4cd4b0e838b91a0
