### ISSUE TITLE
ESM Typescript / ERR_UNSUPPORTED_DIR_IMPORT

### ISSUE THREAD

**Issue by florianbepunkt** [oazapfts/oazapfts#541]
Using this lib in a NodeJS backend within an ESM module, I get the following error: `ERR_UNSUPPORTED_DIR_IMPORT`

I need to manually change
```ts
// from 
import * as Oazapfts from "oazapfts/lib/runtime";
import * as QS from "oazapfts/lib/runtime/query";

// to 
import * as Oazapfts from "oazapfts/lib/runtime/index.js";
import * as QS from "oazapfts/lib/runtime/query.js";
```

**Comment by jonkoops** [comment]
This is how ESM works, this is not a bug in Oazapfts. If you import a file in ESM you will have to specify the full path to it. That said, you should not import files from anything but the top level `oazapfts` namespace. Importing things from `/lib/` will likely break in the future.

**Comment by florianbepunkt** [comment]
Thank you for explaining how ESM works. 

So you need to fix the auto generated code by hand if you use ESM in a Node / Typescript setup. Is this intended? Looks like a bug to me, if you need to fix the module resolution of auto-generated code.

if the lib is not compatible with Node ESM/Typescript setup (which I can understand), a warning in the docs would be nice. I can open a PR if you like.

**Comment by jonkoops** [comment]
Ah, my bad, I did not realize this code was generated. Let me re-open this.

**Comment by jonkoops** [comment]
@Xiphe we'll need to use the [`exports` field](https://nodejs.org/api/packages.html#package-entry-points) in the `package.json` and add explicit entry-points for `oazapfts/runtime` and `oazapfts/codegen` which exports all the required API surface.

**Comment by Xiphe** [comment]
Yeah, that makes sense. For documentation and reproducibility I would like to understand how the generated ts file was transpiled to js

**Comment by florianbepunkt** [comment]
> You're right that the auto-generated code of this lib should support all sorts of environments.
> 
> So to clarify: You're referring to line 7+8 of an API client that has been generated with oazapfts, right? 

Yes.

> As the artifact is a `.ts` file I had expect that the typescript compiler would handle the conversation between different module systems?

Unfortunately not, there is currently an experimental flag to resolve extensionless imports, but afaik this is node's esm behaviour (not a typescript issue. You need to specify full import paths, including file extension (the compiled one, so .js). Also for directory imports with barrel files, you need to specify the barrel file.

So:

```ts
// this... 
import * as Oazapfts from "oazapfts/lib/runtime";
import * as QS from "oazapfts/lib/runtime/query";

// becomes this for ESM
import * as Oazapfts from "oazapfts/lib/runtime/index.js";
import * as QS from "oazapfts/lib/runtime/query.js";
```

**Comment by jonkoops** [comment]
You can do extension-less imports of entry-points that are defined in the `exports` field.

**Comment by Xiphe** [comment]
Thank you both for the input. Will add those entry-points. @florianbepunkt for documentation, would you mind sharing how you transpile the `.ts` artifact to `.js` for use in node? (using `tsc`, `esbuild`, which `tsconfig.json`?)

**Comment by florianbepunkt** [comment]
> You can do extension-less imports of entry-points that are defined in the exports field.

Absolutely. But it's important to grasp the concept, the exports field acts as an alias, pointing to a resolvable path. 

> @florianbepunkt for documentation, would you mind sharing how you transpile the .ts artifact to .js for use in node? (using tsc, esbuild, which tsconfig.json?)

We use both. This is the tsconfig

```json
{
  "compilerOptions": {
    "noErrorTruncation": true,
    "incremental": false,
    "target": "ESNext",
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable"
    ] ,
    "module": "NodeNext",
    "moduleResolution": "bundler",
    "declaration": true,
    "sourceMap": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "include": ["src", "bin", "chore"],
    "exclude": ["**/node_modules", "**/.*/", "cdk.out", "**/*.json"]
  }
}

```

**Comment by Xiphe** [comment]
Awesome, thank you. Can you give `oazapfts@5.0.3-exports.1` a shot?

**Comment by florianbepunkt** [comment]
@Xiphe Looks good to me. Thank you.
