### ISSUE TITLE
Documentation/Feature request: Server selection

### ISSUE THREAD

**Issue by florianbepunkt** [oazapfts/oazapfts#543]
Does oazapft support server variables? If so how would you use them. If not, this is a feature request.

Example
```json
{
   "openapi": "3.0.2",
   "servers": [
      {
         "url": "https://{environment}.example.de",
         "variables": {
            "environment": {
               "default": "api",
               "enum": [
                  "api",
                  "api.dev",
                  "api.staging"
               ]
            }
         }
      }
   ]
}
```

**Comment by Xiphe** [comment]
I don't think this is supported yet 👍

**Comment by bdm-k** [comment]
I find it natural to specify server variables using `RequestOpts`. However, to enforce strict typing, we have to make `RequestOpts` generic, something like:
```TypeScript
export type RequestOpts<T> = {
  baseUrl?: string;
  fetch?: typeof fetch;
  formDataConstructor?: new () => FormData;
  headers?: HeadersInit | CustomHeaders;
  server_variables?: T;
} & Omit<RequestInit, "body" | "headers">;
```
Take the example at the top, `T` should be
```TypeScript
```

**Comment by Xiphe** [comment]
seems feasible. T should default to void.

**Comment by bdm-k** [comment]
I discovered that server variables are taken into consideration when generating the `servers` constant. I’m not sure what is the intended purpose of this constant. I’m thinking that it might be an option to utilize the constant.

**Comment by Xiphe** [comment]
I feel like understanding the use-cases here would make sense. Its not really clear to me

**Comment by florianbepunkt** [comment]
A good overview of uses cases is described here: https://swagger.io/docs/specification/api-host-and-base-path/

> Common use cases for server templating:
> Specifying multiple protocols (such as HTTP vs HTTPS).
> SaaS (hosted) applications where each customer has their own subdomain.
> Regional servers in different geographical regions (example: Amazon Web Services).
> Single API definition for SaaS and on-premise APIs.

At our company we use different environments (dev, staging, prod) and use templating for the api base url (api.service.de, dev.api.service.de, staging.api.service.de, etc). We wrote a thin wrapper around oazapft for this.

**Comment by Xiphe** [comment]
Let's keep the generated code platform agnostic and not use environment variables. 
The use cases described suggest that usually this would be global configuration. Our API for this is the `defaults` export.

```ts
import { defaults, servers } from "./myGeneratedApi.ts";

defaults.baseUrl = servers.prod;
```

the `Defaults` extend `RequestOpts` so i think it the [suggestion from @bdm-k ](https://github.com/oazapfts/oazapfts/issues/543#issuecomment-1954805427) would fit here.

What do you say @florianbepunkt, what would your expected usage of this? Where and when would you expect to set server variables?

**Comment by florianbepunkt** [comment]
Not sure if variables in the OpenAPI spec are purely scoped to server base urls – this is the only place we are using them. If they are, a function that takes a dict of variables as input and outputs the templated string would make sense to me.

Example:

```ts
const spec = {
  servers: [
    {
      url: "{protocol}://{environment}.your-domain.de/identity",
      variables: {
        environment: {
          default: "api",
          enum: ["api", "api.dev", "api.test", "api.staging"],
        },
        protocol: {
          default: "https",
          enum: ["https", "http"],
        },
      },
    },
  ],
}

defaults.baseUrl = await someFnFromOazapft({ protocol: "https://", environment: Promise.resolve("api.test") }); // returns "https://api.test.your-domain.de/identity",


```

**Comment by Xiphe** [comment]
This makes sense, thank you for the input.

1. Let's get confirmation where server variables are meant to be used. 
2. I like the api you're proposing here, we might even just provide server factories on the `servers` object when a serve has variables.

```ts
// myGeneratedApi.ts
/**
 * DO NOT MODIFY - This file has been generated using oazapfts.
 * See https://www.npmjs.com/package/oazapfts
 */
import { applyServerVariables } from "@oazapfts/runtime/servers";

// ...other code

export const servers = {
  server1: "https://petstore.swagger.io/v2",
  server2: (
    serverVariables: { protocol: 'https://' | 'http://',
    environment: 'prod' | 'staging' | 'test' }
  ) => (
    applyServerVariables("{protocol}://{environment}.your-domain.de/identity", serverVariables)
  )
};
```

```ts
// code using the client
import { defaults, servers } from './myGeneratedApi.ts';

defaults.baseUrl = servers.server2({ protocol: "https://", environment: "prod" });
```

I'm afraid we'd either only allow sync values here or deal with the promises internally. I would not want to require top level await here.

**Comment by bdm-k** [comment]
Current Oazapfts can already generate that function. So, I believe this issue is about the documentation.

**Comment by Xiphe** [comment]
lol. I wasn't aware of that :)

**Comment by Xiphe** [comment]
So yeah, thanks @bdm-k for pointing this out. This is already working:

```ts
// code using the client
import { defaults, servers } from './myGeneratedApi.ts';

defaults.baseUrl = servers.server2({ protocol: "https://", environment: "prod" });
```
