### ISSUE TITLE
Type error when trying to set default headers

### ISSUE THREAD

**Issue by JeanSummers** [oazapfts/oazapfts#551]
After updating to latest version I got sudden type error. This code works fine in runtime, but typescript is complaining
![image](https://github.com/oazapfts/oazapfts/assets/26025155/534f0ef6-d2c2-452e-b633-ffd1f1e0553c)

**Comment by Xiphe** [comment]
Good catch! This is a regression introduced with https://github.com/oazapfts/oazapfts/releases/tag/v5.0.0 going to add a fix now
