### ISSUE TITLE
Cannot find module '@oazapfts/runtime/query' or its corresponding type declarations.

### ISSUE THREAD

**Issue by twastvedt** [oazapfts/oazapfts#578]
After upgrading to oazapfts 6.0.2, runtime 1.0.0 I'm getting the above error on this line in the generated Typescript file:
```
import * as QS from "@oazapfts/runtime/query";
```
`QS` is also unused in the file, but that may just be because of my particular API.

**Comment by Xiphe** [comment]
Hi @twastvedt 

That's a bummer! Can you share your tsconfig.json?

> QS is also unused in the file, but that may just be because of my particular API.

Yeah that will probably be the reason. We might want to explore adding the import conditionally 🤔

**Comment by twastvedt** [comment]
Ah. Looks like it's a result of not having a `moduleResolution` of `node16`, `nodeNext`, or `bundler`. The import works if I change that, but then other things break. For now I'll just remove that line manually I think.

- node 20.10.0
- Typescript 5.3.3
- CJS vs ESM: Not sure, how do I find this out?
- No `"type": "module"` in project.json.

**tsconfig**
```
{
    "compilerOptions": {
        "target": "es2015",
        "allowSyntheticDefaultImports": true,
        "jsx": "react",
        "module": "ESNext",
        "moduleResolution": "node",
        "noImplicitAny": true,
        "skipLibCheck": false,
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        },
    "exclude": [
        "node_modules"
    ], 
    "compileOnSave": false,
    "awesomeTypescriptLoaderOptions": {
        "useCache": true,
        // add diagnostics ignore for TS- checks happening in node-module packages
        "ignoreDiagnostics": [1005, 2300, 2304, 2305, 2307, 2322, 2339, 2503, 2536, 2574, 2694, 2693, 2695]
    }
}
```

**Comment by Xiphe** [comment]
Ah, I see... the problem is that `"moduleResolution": "node",` does not respect the "exports" fields and instead only works on the fs level. I'd be open to bundle the package in a way that both work. Would that help?

A quick-fix would be to add this to your tsconfig

```json
  "compilerOptions": {
   "paths": {
      "@oazapfts/runtime/query": ["./node_modules/@oazapfts/runtime/dist/query"]
    }
```

**Comment by Xiphe** [comment]
Can you please give `6.0.3-beta.1` a shot? It should support `node` module resolution

**Comment by twastvedt** [comment]
Yup, that works. Thank you!
