### ISSUE TITLE
Wrong imports on generated files

### ISSUE THREAD

**Issue by Tiagoperes** [oazapfts/oazapfts#583]
The generated files have the following imports:

```ts
import * as Oazapfts from "@oazapfts/runtime";
import * as QS from "@oazapfts/runtime/query";
```

None of these paths exist.

1. The package is called "oazapfts", not "@oazapfts";
2. There's no such folder "oazapfts/runtime" in the bundled package.

**Comment by Tiagoperes** [comment]
Oh. I just got it! The new version separates runtime from code generation. I'll make a PR updating the docs.

**Comment by Xiphe** [comment]
Glad you were able to fix this yourself. Sorry for the confusion 🙃
