### ISSUE TITLE
Enum names Type and Type2.

### ISSUE THREAD

**Issue by 2Fast2BCn** [oazapfts/oazapfts#590]
When using `npx @rtk-query/codegen-openapi` (which I think uses this project) and you have the following in `swagger.json`
```
{
...
  "definitions": {
    "Attachment": {
      ...
      "type": {
        "type": "string",
        "enum": [
          "picture",
          "document",
          ...
        ],
        "x-ts-type": "AttachmentType"
      },
    },
    ...
    "Company": {
      ...
      "type": {
        "type": "string",
        "enum": [
          "inc",
          ..
        ],
        "x-ts-type": "CompanyType"
      },
    },
...
}
```
Then codegen-openapi generates enums `Type`, `Type2` is there a way to make it generate `AttachmentType`  and `CompanyType`  instead?

**Comment by Xiphe** [comment]
Just found that this might already be possible using `title` instead of `x-ts-type`? Can we check that?

**Comment by 2Fast2BCn** [comment]
Yes, let's use what already exists.

**Comment by Xiphe** [comment]
Cool! Sorry that I was so late finding this, could have saved you some work :/
