### ISSUE TITLE
Api returns JSON.stringified values.

### ISSUE THREAD

**Issue by fmonper1** [oazapfts/oazapfts#597]
I recently updated a project form oazapfts v4 to v6 and since then every value returned from my API has te correct typescript types from my api, but the actual values are strings.

I've been able to work around it doing this dirty hack:

```
    const response = await createBusinessAndGetBucketUrlMutation.mutateAsync({
      organizationId,
      body: { ...data, fileNames: data.files.map((file) => file.name) },
    });

    // response has the correct Tpescript type, but throws a runtime error since its actually a string that can't be destructured as an object
    const { fileUrls, business } = JSON.parse(
      response.toString(),
    ) as typeof response; // typeof response has the correct type
```

Something must be wrong with the internal `oazapfts.fetchJson` function. 

This is the generated code from my optimistc api:

```
export function createBusinessAndGetBucketUrl(
  {
    organizationId,
    body,
  }: {
    organizationId: string;
    body: {
      businessName: string;
      website: string;
      industry: string;
      type: string;
      fileNames: string[];
    };
  },
  opts?: Oazapfts.RequestOpts,
) {
  return oazapfts.ok(
    oazapfts.fetchJson<
      | {
          status: 200;
          data: {
            business: {
              id: string;
              backgroundImage: string | null;
              website: string | null;
              type: string | null;
              industry: string | null;
              contextReady: boolean;
              contextJobId: string | null;
              bgColor: string;
              businessName: string;
              organizationId: string;
              creatorId: string;
              createdAt: string;
              updatedAt: string;
            };
            fileUrls: string[];
          };
        }
      | {
          status: 400;
          data: {
            message: string;
          };
        }
    >(
      `/api/v2/business/organization/${encodeURIComponent(organizationId)}/`,
      oazapfts.json({
        ...opts,
        method: "POST",
        body,
      }),
    ),
  );
}
```

``

**Comment by GenerousSimon** [comment]
I ran into this issue too, had a look at the @oazapfts/runtime src (looking for JSON.parse), and you can see it is searching the headers for "json" in the Content-Type before choosing to JSON.parse it (or not). When I looked at my server responses more carefully I noticed ```"Content-Type": "text/plain"```, so changing my headers on the serverside to return ```"Content-Type": "application/json"``` fixed this for me - if that's helpful.

**Comment by Xiphe** [comment]
Sorry for the late reply. And thanks for chiming in @GenerousSimon 

@fmonper1 have you been able to check if this might be related to the response content type?

From looking at the code, this [behavior had been there since v4](https://github.com/oazapfts/oazapfts/blob/5f0c5f901074c23e9a16617613eb69f9cb9ed98b/src/runtime/index.ts#L60-L68), possibly earlier so this does not explain why the update broke your setup.

Could you please double-check if downgrading to v4 fixes the issue?

I'm closing here since I assume it's a problem with our server. Please re-open when someone can confirm it's oazapfts related.
